/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinuxRouteImport } from './routes/linux'
import { Route as FungalHandbookRouteImport } from './routes/fungal-handbook'
import { Route as FungalRouteImport } from './routes/fungal'
import { Route as BacterialHandbookRouteImport } from './routes/bacterial-handbook'
import { Route as BacterialRouteImport } from './routes/bacterial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FungalHandbookChapterChapterIdRouteImport } from './routes/fungal-handbook.chapter.$chapterId'
import { Route as BacterialHandbookChapterChapterIdRouteImport } from './routes/bacterial-handbook.chapter.$chapterId'

const LinuxRoute = LinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => rootRouteImport,
} as any)
const FungalHandbookRoute = FungalHandbookRouteImport.update({
  id: '/fungal-handbook',
  path: '/fungal-handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const FungalRoute = FungalRouteImport.update({
  id: '/fungal',
  path: '/fungal',
  getParentRoute: () => rootRouteImport,
} as any)
const BacterialHandbookRoute = BacterialHandbookRouteImport.update({
  id: '/bacterial-handbook',
  path: '/bacterial-handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const BacterialRoute = BacterialRouteImport.update({
  id: '/bacterial',
  path: '/bacterial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FungalHandbookChapterChapterIdRoute =
  FungalHandbookChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => FungalHandbookRoute,
  } as any)
const BacterialHandbookChapterChapterIdRoute =
  BacterialHandbookChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => BacterialHandbookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/bacterial-handbook': typeof BacterialHandbookRouteWithChildren
  '/fungal': typeof FungalRoute
  '/fungal-handbook': typeof FungalHandbookRouteWithChildren
  '/linux': typeof LinuxRoute
  '/bacterial-handbook/chapter/$chapterId': typeof BacterialHandbookChapterChapterIdRoute
  '/fungal-handbook/chapter/$chapterId': typeof FungalHandbookChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/bacterial-handbook': typeof BacterialHandbookRouteWithChildren
  '/fungal': typeof FungalRoute
  '/fungal-handbook': typeof FungalHandbookRouteWithChildren
  '/linux': typeof LinuxRoute
  '/bacterial-handbook/chapter/$chapterId': typeof BacterialHandbookChapterChapterIdRoute
  '/fungal-handbook/chapter/$chapterId': typeof FungalHandbookChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/bacterial-handbook': typeof BacterialHandbookRouteWithChildren
  '/fungal': typeof FungalRoute
  '/fungal-handbook': typeof FungalHandbookRouteWithChildren
  '/linux': typeof LinuxRoute
  '/bacterial-handbook/chapter/$chapterId': typeof BacterialHandbookChapterChapterIdRoute
  '/fungal-handbook/chapter/$chapterId': typeof FungalHandbookChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bacterial'
    | '/bacterial-handbook'
    | '/fungal'
    | '/fungal-handbook'
    | '/linux'
    | '/bacterial-handbook/chapter/$chapterId'
    | '/fungal-handbook/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bacterial'
    | '/bacterial-handbook'
    | '/fungal'
    | '/fungal-handbook'
    | '/linux'
    | '/bacterial-handbook/chapter/$chapterId'
    | '/fungal-handbook/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bacterial'
    | '/bacterial-handbook'
    | '/fungal'
    | '/fungal-handbook'
    | '/linux'
    | '/bacterial-handbook/chapter/$chapterId'
    | '/fungal-handbook/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacterialRoute: typeof BacterialRoute
  BacterialHandbookRoute: typeof BacterialHandbookRouteWithChildren
  FungalRoute: typeof FungalRoute
  FungalHandbookRoute: typeof FungalHandbookRouteWithChildren
  LinuxRoute: typeof LinuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linux': {
      id: '/linux'
      path: '/linux'
      fullPath: '/linux'
      preLoaderRoute: typeof LinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fungal-handbook': {
      id: '/fungal-handbook'
      path: '/fungal-handbook'
      fullPath: '/fungal-handbook'
      preLoaderRoute: typeof FungalHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fungal': {
      id: '/fungal'
      path: '/fungal'
      fullPath: '/fungal'
      preLoaderRoute: typeof FungalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacterial-handbook': {
      id: '/bacterial-handbook'
      path: '/bacterial-handbook'
      fullPath: '/bacterial-handbook'
      preLoaderRoute: typeof BacterialHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacterial': {
      id: '/bacterial'
      path: '/bacterial'
      fullPath: '/bacterial'
      preLoaderRoute: typeof BacterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fungal-handbook/chapter/$chapterId': {
      id: '/fungal-handbook/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/fungal-handbook/chapter/$chapterId'
      preLoaderRoute: typeof FungalHandbookChapterChapterIdRouteImport
      parentRoute: typeof FungalHandbookRoute
    }
    '/bacterial-handbook/chapter/$chapterId': {
      id: '/bacterial-handbook/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/bacterial-handbook/chapter/$chapterId'
      preLoaderRoute: typeof BacterialHandbookChapterChapterIdRouteImport
      parentRoute: typeof BacterialHandbookRoute
    }
  }
}

interface BacterialHandbookRouteChildren {
  BacterialHandbookChapterChapterIdRoute: typeof BacterialHandbookChapterChapterIdRoute
}

const BacterialHandbookRouteChildren: BacterialHandbookRouteChildren = {
  BacterialHandbookChapterChapterIdRoute:
    BacterialHandbookChapterChapterIdRoute,
}

const BacterialHandbookRouteWithChildren =
  BacterialHandbookRoute._addFileChildren(BacterialHandbookRouteChildren)

interface FungalHandbookRouteChildren {
  FungalHandbookChapterChapterIdRoute: typeof FungalHandbookChapterChapterIdRoute
}

const FungalHandbookRouteChildren: FungalHandbookRouteChildren = {
  FungalHandbookChapterChapterIdRoute: FungalHandbookChapterChapterIdRoute,
}

const FungalHandbookRouteWithChildren = FungalHandbookRoute._addFileChildren(
  FungalHandbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacterialRoute: BacterialRoute,
  BacterialHandbookRoute: BacterialHandbookRouteWithChildren,
  FungalRoute: FungalRoute,
  FungalHandbookRoute: FungalHandbookRouteWithChildren,
  LinuxRoute: LinuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
