/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinuxRouteImport } from './routes/linux'
import { Route as FungalRouteImport } from './routes/fungal'
import { Route as BacterialRouteImport } from './routes/bacterial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LinuxRoute = LinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => rootRouteImport,
} as any)
const FungalRoute = FungalRouteImport.update({
  id: '/fungal',
  path: '/fungal',
  getParentRoute: () => rootRouteImport,
} as any)
const BacterialRoute = BacterialRouteImport.update({
  id: '/bacterial',
  path: '/bacterial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
  '/linux': typeof LinuxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
  '/linux': typeof LinuxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
  '/linux': typeof LinuxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/bacterial' | '/fungal' | '/linux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/bacterial' | '/fungal' | '/linux'
  id: '__root__' | '/' | '/about' | '/bacterial' | '/fungal' | '/linux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacterialRoute: typeof BacterialRoute
  FungalRoute: typeof FungalRoute
  LinuxRoute: typeof LinuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linux': {
      id: '/linux'
      path: '/linux'
      fullPath: '/linux'
      preLoaderRoute: typeof LinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fungal': {
      id: '/fungal'
      path: '/fungal'
      fullPath: '/fungal'
      preLoaderRoute: typeof FungalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacterial': {
      id: '/bacterial'
      path: '/bacterial'
      fullPath: '/bacterial'
      preLoaderRoute: typeof BacterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacterialRoute: BacterialRoute,
  FungalRoute: FungalRoute,
  LinuxRoute: LinuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
