/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FungalRouteImport } from './routes/fungal'
import { Route as BacterialRouteImport } from './routes/bacterial'
import { Route as IndexRouteImport } from './routes/index'

const FungalRoute = FungalRouteImport.update({
  id: '/fungal',
  path: '/fungal',
  getParentRoute: () => rootRouteImport,
} as any)
const BacterialRoute = BacterialRouteImport.update({
  id: '/bacterial',
  path: '/bacterial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bacterial': typeof BacterialRoute
  '/fungal': typeof FungalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bacterial' | '/fungal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bacterial' | '/fungal'
  id: '__root__' | '/' | '/bacterial' | '/fungal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacterialRoute: typeof BacterialRoute
  FungalRoute: typeof FungalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fungal': {
      id: '/fungal'
      path: '/fungal'
      fullPath: '/fungal'
      preLoaderRoute: typeof FungalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacterial': {
      id: '/bacterial'
      path: '/bacterial'
      fullPath: '/bacterial'
      preLoaderRoute: typeof BacterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacterialRoute: BacterialRoute,
  FungalRoute: FungalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
